### ISSUE TITLE
Github Action for this fork

### ISSUE THREAD

**Issue by arBmind** [cristianadam/ccache#4]
### Question ###

Hi @cristianadam,
I found your comments on https://github.com/ccache/ccache/discussions/447 and also saw your fork was used by QtCreator cmake builds. Great work!
The effort to integrate your fork into a Github Actions workflow is quite extensive.

I maintain a fork of QtCreator that builds with Qbs on Github Actions. I like the speedup of the CMake build, but not the effort.
I was thinking about simplifying this by creating a dedicated Github Action.

See: https://github.com/hendrikmuhs/ccache-action (only Ubuntu and MacOS) or https://github.com/mikehardy/buildcache-action (all OSs)

Do you know of a Github Action of your fork? Do you want to create and maintain it? If not, do you have some hints for me?

**Comment by cristianadam** [comment]
My fork of ccache will no longer be needed since the MSVC support is already part of ccache main branch and will be part of the next 4.6 release.

Then one could simply update the provisioning part of the GitHub Actions jobs with the `apt`, `brew` or `choco` package managers.

I haven't done any GitHub Actions work myself, I'm not familiar with the `node.js`, `typescript` bits that they require. I'm fine with having a few CMake script lines in a yml file.

**Comment by arBmind** [comment]
Ok, I will wait for 4.6 release of ccache then.
